supermercados_config = {
    "mercadona": {
        "secciones": {
            #fruta y verdura
            "fruta": "https://tienda.mercadona.es/categories/27",
            "ensalada": "https://tienda.mercadona.es/categories/28",
            "verdura": "https://tienda.mercadona.es/categories/29",
            #aceite, especias y salsas
            "aceite, vinagre y sal": "https://tienda.mercadona.es/categories/112",
            "especias": "https://tienda.mercadona.es/categories/115",
            "mayonesa, ketchup y mostaza": "https://tienda.mercadona.es/categories/116",
            "mayonesa, ketchup y mostaza": "https://tienda.mercadona.es/categories/117",
            #agua y refrescos
            "agua": "https://tienda.mercadona.es/categories/156",
            "isotonico y energetico": "https://tienda.mercadona.es/categories/163",
            "refresco de cola": "https://tienda.mercadona.es/categories/158",
            "refresco de naranja y de limon": "https://tienda.mercadona.es/categories/159",
            "tonica y bitter": "https://tienda.mercadona.es/categories/161",
            "refresco de te y sin gas": "https://tienda.mercadona.es/categories/162",
            #aperitivos
            "aceitunas y encurtidos": "https://tienda.mercadona.es/categories/135",
            "frutos secos y fruta desecada": "https://tienda.mercadona.es/categories/133",
            "patatas fritas y snacks": "https://tienda.mercadona.es/categories/132",
            #arroz, legumbres y pasta
            "arroz": "https://tienda.mercadona.es/categories/118",
            "legumbres": "https://tienda.mercadona.es/categories/121",
            "pasta y fideos": "https://tienda.mercadona.es/categories/120",
            #azúcar, caramelos y chocolate
            "azúcar y edulcorante": "https://tienda.mercadona.es/categories/89",
            "chicles y caramelos": "https://tienda.mercadona.es/categories/95",
            "chocolate": "https://tienda.mercadona.es/categories/92",
            "golosinas": "https://tienda.mercadona.es/categories/97",
            "mermelada y miel": "https://tienda.mercadona.es/categories/90",
            #bebé
            "alimentación infantil": "https://tienda.mercadona.es/categories/216",
            "biberón y chupete": "https://tienda.mercadona.es/categories/219",
            "higiene y cuidado": "https://tienda.mercadona.es/categories/218",
            "toallitas y pañales": "https://tienda.mercadona.es/categories/217",
            #bodega
            "cerveza": "https://tienda.mercadona.es/categories/164",
            "cerveza sin alcohol": "https://tienda.mercadona.es/categories/166",
            "licores": "https://tienda.mercadona.es/categories/181",
            "sidra y cava": "https://tienda.mercadona.es/categories/174",
            "tinto de verano y sangría": "https://tienda.mercadona.es/categories/168",
            "vino blanco": "https://tienda.mercadona.es/categories/170",
            "vino lambrusco y espumoso": "https://tienda.mercadona.es/categories/173",
            "vino rosado": "https://tienda.mercadona.es/categories/171",
            "vino tinto": "https://tienda.mercadona.es/categories/169",
            #cacao, café e infusiones
            "cacao soluble y chocolate a la taza": "https://tienda.mercadona.es/categories/86",
            "café cápsula y monodosis": "https://tienda.mercadona.es/categories/81",
            "café molido y en grano": "https://tienda.mercadona.es/categories/83",
            "café soluble y otras bebidas": "https://tienda.mercadona.es/categories/84",
            "té e infusiones": "https://tienda.mercadona.es/categories/88",
            #carne
            "arreglos": "https://tienda.mercadona.es/categories/46",
            "aves y pollo": "https://tienda.mercadona.es/categories/38",
            "carne congelada": "https://tienda.mercadona.es/categories/47",
            "cerdo": "https://tienda.mercadona.es/categories/37",
            "conejo y cordero": "https://tienda.mercadona.es/categories/42",
            "embutido": "https://tienda.mercadona.es/categories/43",
            "hamburguesas y picadas": "https://tienda.mercadona.es/categories/44",
            "vacuno": "https://tienda.mercadona.es/categories/40",
            "empanados y elaborados": "https://tienda.mercadona.es/categories/45",
            #cereales y galletas
            "cereales": "https://tienda.mercadona.es/categories/78",
            "galletas": "https://tienda.mercadona.es/categories/80",
            "tortitas": "https://tienda.mercadona.es/categories/79",
            #charcutería y quesos
            "aves y jamon cocido": "https://tienda.mercadona.es/categories/48",
            "bacon y salchichas": "https://tienda.mercadona.es/categories/52",
            "chopped y mortadela": "https://tienda.mercadona.es/categories/49",
            "embutido curado": "https://tienda.mercadona.es/categories/51",
            "jamon serrano": "https://tienda.mercadona.es/categories/50",
            "pate y sobrasada": "https://tienda.mercadona.es/categories/58",
            "queso curado, semicurado y tierno": "https://tienda.mercadona.es/categories/54",
            "queso lonchas, rallado y en porciones": "https://tienda.mercadona.es/categories/56",
            "queso untable y fresco": "https://tienda.mercadona.es/categories/53",
            #congelados
            "arroz y pasta": "https://tienda.mercadona.es/categories/147",
            "carne": "https://tienda.mercadona.es/categories/148",
            "helados": "https://tienda.mercadona.es/categories/154",
            "hielo": "https://tienda.mercadona.es/categories/155",
            "marisco": "https://tienda.mercadona.es/categories/150",
            "pescado": "https://tienda.mercadona.es/categories/149",
            "pizzas": "https://tienda.mercadona.es/categories/151",
            "rebozados": "https://tienda.mercadona.es/categories/884",
            "tartas y churros": "https://tienda.mercadona.es/categories/152",
            "verdura": "https://tienda.mercadona.es/categories/145",
            #conservas, caldos y cremas
            "atun y otras conservas de pescado": "https://tienda.mercadona.es/categories/122",
            "berberechos y mejillones": "https://tienda.mercadona.es/categories/123",
            "conservas de verdura y frutas": "https://tienda.mercadona.es/categories/127",
            "gazpacho y cremas": "https://tienda.mercadona.es/categories/130",
            "sopa y caldo": "https://tienda.mercadona.es/categories/129",
            "tomate": "https://tienda.mercadona.es/categories/126",
            #cuidado del cabello
            "acondicionador y mascarilla": "https://tienda.mercadona.es/categories/201",
            "champu": "https://tienda.mercadona.es/categories/199",
            "coloracion cabello": "https://tienda.mercadona.es/categories/203",
            "fijacion cabello": "https://tienda.mercadona.es/categories/202",
            #cuidado facial y corporal
            "afeitado y cuidado para hombre": "https://tienda.mercadona.es/categories/192",
            "cuidado corporal": "https://tienda.mercadona.es/categories/189",
            "cuidado e higiene facial": "https://tienda.mercadona.es/categories/185",
            "depilacion": "https://tienda.mercadona.es/categories/191",
            "desodorante": "https://tienda.mercadona.es/categories/188",
            "gel y jabon de manos": "https://tienda.mercadona.es/categories/187",
            "higiene bucal": "https://tienda.mercadona.es/categories/186",
            "higiene intima": "https://tienda.mercadona.es/categories/190",
            "manicura y pedicura": "https://tienda.mercadona.es/categories/194",
            "perfume y colonia": "https://tienda.mercadona.es/categories/196",
            "protector solar y aftersun": "https://tienda.mercadona.es/categories/198",
            #fitoterapia y parafarmacia
            "fitoterapia": "https://tienda.mercadona.es/categories/213",
            "parafarmacia": "https://tienda.mercadona.es/categories/214",
            #fruta y verdura
            "fruta": "https://tienda.mercadona.es/categories/27",
            "lechuga y ensalada preparada": "https://tienda.mercadona.es/categories/28",
            "verdura": "https://tienda.mercadona.es/categories/29",
            #huevos, leche y mantequilla
            "huevos": "https://tienda.mercadona.es/categories/77",
            "leche y bebidas vegetales": "https://tienda.mercadona.es/categories/72",
            "mantequilla y margarina": "https://tienda.mercadona.es/categories/75",
            #limpieza y hogar
            "detergente y suavizante ropa": "https://tienda.mercadona.es/categories/226",
            "estropajo, bayeta y guantes": "https://tienda.mercadona.es/categories/237",
            "insecticida y ambientador": "https://tienda.mercadona.es/categories/241",
            "lejia y liquidos fuertes": "https://tienda.mercadona.es/categories/234",
            "limpiacristales": "https://tienda.mercadona.es/categories/235",
            "limpiahogar y friegasuelos": "https://tienda.mercadona.es/categories/233",
            "limpieza baño y wc": "https://tienda.mercadona.es/categories/231",
            "limpieza cocina": "https://tienda.mercadona.es/categories/230",
            "limpieza muebles y multiusos": "https://tienda.mercadona.es/categories/232",
            "limpieza vajilla": "https://tienda.mercadona.es/categories/229",
            "menaje y conservacion de alimentos": "https://tienda.mercadona.es/categories/243",
            "papel higienico y celulosa": "https://tienda.mercadona.es/categories/238",
            "pilas y bolsas de basura": "https://tienda.mercadona.es/categories/239",
            "utensilios de limpieza y calzado": "https://tienda.mercadona.es/categories/244",
            #maquillaje
            "bases de maquillaje y corrector": "https://tienda.mercadona.es/categories/206",
            "colorete y polvos": "https://tienda.mercadona.es/categories/207",
            "labios": "https://tienda.mercadona.es/categories/208",
            "ojos": "https://tienda.mercadona.es/categories/210",
            "pinceles y brochas": "https://tienda.mercadona.es/categories/212",
            #marisco y pescado
            "marisco": "https://tienda.mercadona.es/categories/32",
            "pescado congelado": "https://tienda.mercadona.es/categories/34",
            "pescado fresco": "https://tienda.mercadona.es/categories/31",
            "salazones y ahumados": "https://tienda.mercadona.es/categories/36",
            #mascotas
            "gato": "https://tienda.mercadona.es/categories/222",
            "perro": "https://tienda.mercadona.es/categories/221",
            "otros": "https://tienda.mercadona.es/categories/225",
            #panaderia y pasteleria
            "bolleria de horno": "https://tienda.mercadona.es/categories/65",
            "bolleria envasada": "https://tienda.mercadona.es/categories/66",
            "harina y preparado reposteria": "https://tienda.mercadona.es/categories/69",
            "pan de horno": "https://tienda.mercadona.es/categories/59",
            "pan de molde y otras especialidades": "https://tienda.mercadona.es/categories/60",
            "pan tostado y rallado": "https://tienda.mercadona.es/categories/62",
            "picos, rosquilletas y picatostes": "https://tienda.mercadona.es/categories/64",
            "tartas y pasteles": "https://tienda.mercadona.es/categories/68",
            "velas y decoracion": "https://tienda.mercadona.es/categories/71",
            #pizzas y platos preparados
            "listo para comer": "https://tienda.mercadona.es/categories/897",
            "pizzas": "https://tienda.mercadona.es/categories/138",
            "platos preparados calientes": "https://tienda.mercadona.es/categories/140",
            "platos preparados frios": "https://tienda.mercadona.es/categories/142",
            #postres y yogures
            "bifidus": "https://tienda.mercadona.es/categories/105",
            "flan y natillas": "https://tienda.mercadona.es/categories/110",
            "gelatina y otros postres": "https://tienda.mercadona.es/categories/111",
            "postres de soja": "https://tienda.mercadona.es/categories/106",
            "yogures desnatados": "https://tienda.mercadona.es/categories/103",
            "yogures griegos": "https://tienda.mercadona.es/categories/109",
            "yogures liquidos": "https://tienda.mercadona.es/categories/108",
            "yogures naturales y sabores": "https://tienda.mercadona.es/categories/104",
            "yogures y postres infantiles": "https://tienda.mercadona.es/categories/107",
            #zumos
            "fruta variada": "https://tienda.mercadona.es/categories/99",
            "melocoton y piña": "https://tienda.mercadona.es/categories/100",
            "naranja": "https://tienda.mercadona.es/categories/143",
            "tomate y otros sabores": "https://tienda.mercadona.es/categories/98",
            
        },
        "selectores": {
            "producto": ".product-cell",
            "nombre": ".product-cell__description-name",
            "precio": ".product-price__unit-price",
        },
    },
    "alcampo": {
        "secciones": {
            #frescos
            "frutas": "https://www.compraonline.alcampo.es/categories/frescos/frutas/OC1701?sortBy=favorite",
            "verduras y hortalizas": "https://www.compraonline.alcampo.es/categories/frescos/verduras-y-hortalizas/OC1702?sortBy=favorite",
            "carne": "https://www.compraonline.alcampo.es/categories/frescos/carne/OC13?sortBy=favorite",
            "pescados, mariscos y moluscos": "https://www.compraonline.alcampo.es/categories/frescos/pescados-mariscos-y-moluscos/OC14?sortBy=favorite",
            "ahumados, surimis, anchoas, pulpos y otros": "https://www.compraonline.alcampo.es/categories/frescos/ahumados-surimis-anchoas-pulpos-y-otros/OC184?sortBy=favorite",
            "charcuteria": "https://www.compraonline.alcampo.es/categories/frescos/charcuter%C3%ADa/OC15?sortBy=favorite",
            "jamones y paletas": "https://www.compraonline.alcampo.es/categories/frescos/jamones-y-paletas/OC151001?sortBy=favorite",
            "quesos": "https://www.compraonline.alcampo.es/categories/frescos/quesos/OCQuesos?sortBy=favorite",
            "panaderia": "https://www.compraonline.alcampo.es/categories/frescos/panader%C3%ADa/OC1281?sortBy=favorite",
            "pasteleria": "https://www.compraonline.alcampo.es/categories/frescos/pasteler%C3%ADa/OC1282?sortBy=favorite",
            #leche, huevos, yogures y lacteos
            "leche, huevos, yogures y lacteos": "https://www.compraonline.alcampo.es/categories/leche-huevos-l%C3%A1cteos-yogures-y-bebidas-vegetales/OC16?sortBy=favorite",
            #alimentacion
            "alimentacion": "https://www.compraonline.alcampo.es/categories/folletos-y-promociones/folleto-alimentaci%C3%B3n-excepto-canarias/alimentaci%C3%B3n/OCALI?sortBy=favorite",
            #desayuno y merienda
            "desayuno y merienda": "https://www.compraonline.alcampo.es/categories/desayuno-y-merienda/OC10?sortBy=favorite",
            #congelados
            "congelados": "https://www.compraonline.alcampo.es/categories/congelados/OC200220183?sortBy=favorite",
            #comida preparada
            "comida preparada": "https://www.compraonline.alcampo.es/categories/comida-preparada/OC20022018?sortBy=favorite",
            "bebidas": "https://www.compraonline.alcampo.es/categories/bebidas/OCC11?sortBy=favorite",
            "supermercado ecologico": "https://www.compraonline.alcampo.es/categories/supermercado-ecol%C3%B3gico/OC26112021?sortBy=favorite",
            "sin gluten / sin lactosa y otras dietas especificas": "https://www.compraonline.alcampo.es/categories/sin-gluten-sin-lactosa-y-otras-dietas-espec%C3%ADficas/OCSINGSINL?sortBy=favorite",
            "veganos": "https://www.compraonline.alcampo.es/categories/veganos/OC09112021?sortBy=favorite",
            "drogueria": "https://www.compraonline.alcampo.es/categories/droguer%C3%ADa/OCC14?sortBy=favorite",
            "perfumeria": "https://www.compraonline.alcampo.es/categories/perfumeria/OC70?sortBy=favorite",
            "bebe": "https://www.compraonline.alcampo.es/categories/beb%C3%A9/OCC13?sortBy=favorite",
            "parafarmacia": "https://www.compraonline.alcampo.es/categories/parafarmacia/OC69?sortBy=favorite",
        },
        "selectores": {
            "producto": ".product-card-container",
            "nombre": ".title-container",
            "precio": ".price-pack-size-container",
        },
    },
    "ahorramas": {
        "secciones": {
            "frescos": "https://www.ahorramas.com/frescos",
            "alimentacion": "https://www.ahorramas.com/alimentacion/?pmin=0.01&start=0&sz=140",
            "bebidas": "https://www.ahorramas.com/bebidas/?pmin=0.01&start=0&sz=20",
            "lacteos": "https://www.ahorramas.com/lacteos/?pmin=0.01&start=0&sz=18",
            "limpieza": "https://www.ahorramas.com/limpieza/?pmin=0.01&start=0&sz=18",
            "cuidado personal": "https://www.ahorramas.com/cuidado-personal/?pmin=0.01&start=0&sz=18",
            "congelados": "https://www.ahorramas.com/congelados/?pmin=0.01&start=0&sz=20",
            "hogar": "https://www.ahorramas.com/hogar/?pmin=0.01&start=0&sz=20",
            "bebe": "https://www.ahorramas.com/bebe/?pmin=0.01&start=0&sz=20",
            "mascotas": "https://www.ahorramas.com/mascotas/?pmin=0.01&start=0&sz=20",
        },
        "selectores": {
            "producto": ".product-tile",
            "nombre": ".pdp-link",
            "precio": ".value",
            "boton_mas_resultados": "button.more" 
        },
    }
,
}